baseurl = "https://kenharris.xyz/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5
enableRobotsTXT = true

[params]
  contentTypeName = "posts"
  defaultTheme = "dark"
  showMenuItems = 2
  showReadingTime = true
  rssFullText = true

[languages]
  [languages.en]
    title = "Ken Harris"
    #subtitle = "A simple theme for Hugo"
    keywords = "kenhv, ken harris, blog"
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "kenhv"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "rss"
        name = "RSS"
        url = "/posts/index.xml"

      [[languages.en.menu.main]]
        identifier = "archive"
        name = "Archive"
        url = "/archive"
